# Number of days of inactivity before an issue becomes stale
daysUntilStale: 60
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 60
# we only want issues
only: 'issues'
# Issues with these labels will never be considered stale
exemptLabels:
  - 'status: accepted'
  - 'status: future'
  - 'status: wip'
  - 'status: needs investigation'
  - 'status: help wanted'
  - 'type: bug'
  - 'type: task'
# Label to use when marking an issue as stale
staleLabel: 'status: stale'
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.
closeComment: >
  This issue has been automatically closed because it has not had
  activity in a long time. Please feel free to reopen it or create a new issue.
