/*
 * Minecraft Development for IntelliJ
 *
 * https://mcdev.io/
 *
 * Copyright (C) 2026 minecraft-dev
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published
 * by the Free Software Foundation, version 3.0 only.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package com.demonwav.mcdev.platform.fabric.creator

import com.demonwav.mcdev.util.SemanticVersion
import java.nio.file.Files
import java.nio.file.Path
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.readText
import kotlin.io.path.writeText

object FabricGradleWrapper {

    val GRADLE_VERSION = SemanticVersion.parse("9.5.0")
    const val LOOM_VERSION = "1.17.13"
    const val MARKER = "# Generated by Stoffe custom MinecraftDev fork"

    private const val RESOURCE_ROOT = "gradle-wrapper"

    fun writeTo(projectRoot: Path) {
        copyResource(projectRoot, "gradlew")
        copyResource(projectRoot, "gradlew.bat")
        copyResource(projectRoot, "gradle/wrapper/gradle-wrapper.jar", "$RESOURCE_ROOT/gradle-wrapper.jar")
        writeWrapperProperties(projectRoot)
        projectRoot.resolve("gradlew").toFile().setExecutable(true, false)
    }

    fun writeIfFabricProject(projectRoot: Path): Boolean {
        if (!isFabricProject(projectRoot)) {
            return false
        }

        writeTo(projectRoot)
        return true
    }

    private fun isFabricProject(projectRoot: Path): Boolean {
        if (projectRoot.resolve("src/main/resources/fabric.mod.json").exists()) {
            return true
        }

        return sequenceOf("build.gradle", "build.gradle.kts")
            .map(projectRoot::resolve)
            .filter { it.exists() }
            .any { it.readText().contains("fabric-loom") }
    }

    private fun copyResource(projectRoot: Path, relativePath: String, resourcePath: String = "$RESOURCE_ROOT/$relativePath") {
        val outputPath = projectRoot.resolve(relativePath)
        outputPath.parent?.createDirectories()
        val bytes = checkNotNull(FabricGradleWrapper::class.java.classLoader.getResourceAsStream(resourcePath)) {
            "Missing Gradle wrapper resource: $resourcePath"
        }.use { it.readAllBytes() }
        Files.write(outputPath, bytes)
    }

    private fun writeWrapperProperties(projectRoot: Path) {
        val wrapperProperties = projectRoot.resolve("gradle/wrapper/gradle-wrapper.properties")
        wrapperProperties.parent.createDirectories()
        wrapperProperties.writeText(
            """
            $MARKER
            distributionBase=GRADLE_USER_HOME
            distributionPath=wrapper/dists
            distributionUrl=https\://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
            networkTimeout=10000
            validateDistributionUrl=true
            zipStoreBase=GRADLE_USER_HOME
            zipStorePath=wrapper/dists
            """.trimIndent() + "\n",
        )
    }
}
