name: Feature request
description: Suggest a new feature
labels: ["status: unverified", "type: enhancement"]
body:
  - type: markdown
    attributes:
      value: DO NOT REQUEST SUPPORT FOR OLDER VERSIONS OF MINECRAFT.
  - type: input
    id: plugin-version
    attributes:
      label: Minecraft Development for IntelliJ plugin version
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description of the feature request
      description: Please try to avoid vague requests. The more details you can give regarding what the feature request is, how it should work, and why it would be useful, the easier it will be to implement. Feel free to be vague if you have a general idea that something might be cool, but these are less likely to be prioritized and may be denied more often.
  - type: markdown
    attributes:
      value: Please note as well that the developers working on this project don't use every platform it supports, at least not extensively. Different developers have differing knowledge about each platform. With this in mind, giving an in-depth explanation of a feature is targeting can be very helpful, as we may not know as much about what you're referring to as you do.