name: Publish Plugin
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Fetch latest submodule updates
        run: git submodule update --remote
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          cache-read-only: true
      - name: Setup tokens
        env:
          JETBRAINS_TOKEN: ${{ secrets.JETBRAINS_TOKEN }}
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
        shell: bash
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=$HOME/.gradle" >> "$GITHUB_ENV"
          echo "mcdev.deploy.token=${JETBRAINS_TOKEN}" > ~/.gradle/gradle.properties
          echo "mcdev.sentry.token=${SENTRY_TOKEN}" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx4G" >> ~/.gradle/gradle.properties
      - name: Get tag name
        id: get_tag
        shell: bash
        # Tag name is reversed from release name due to how IntelliJ parses plugin version numbers
        run: |
          tag_name="$(echo $GITHUB_REF | cut -d / -f 3)"
          echo tag=$tag_name >> $GITHUB_OUTPUT
          version_array=(${tag_name//-/ })
          echo release=${version_array[1]}-${version_array[0]} >> $GITHUB_OUTPUT
      - name: Create Sentry release
        uses: getsentry/action-release@v3
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_ORG: mcdev
          SENTRY_PROJECT: mcdev
          SENTRY_URL: https://sentry.mcdev.io
        with:
          environment: production
          release: ${{ steps.get_tag.outputs.release }}
      - name: Publish plugin
        run: ./gradlew clean :sentryUploadSourceBundleJava :publishPlugin --stacktrace
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: 'Release ${{ steps.get_tag.outputs.release }}'
          body: '## [View all plugin releases here.](https://plugins.jetbrains.com/plugin/8327-minecraft-development/versions/stable/)'
          prerelease: false
          draft: false
          files: build/distributions/*.zip
