name: Windows Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java-version: [8, 11]
    runs-on: windows-latest
    name: JDK ${{ matrix.java-version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - uses: actions/cache@v1
        name: Gradle Caches
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('*.gradle.kts') }}-${{ hashFiles('gradle.properties') }}
          restore-keys: ${{ runner.os }}-gradle-cache-
      - uses: actions/cache@v1
        name: Gradle Wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-wrapper-
      # Gradle build config
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build --no-daemon --stacktrace
      - name: Cleanup
        shell: powershell
        run: |
          Get-ChildItem "$HOME/.gradle/caches/modules-2" -Include *.lock -ErrorAction SilentlyContinue | Remove-Item -Force
          Get-ChildItem "$HOME/.gradle/caches/transforms-1" -Include *.lock -ErrorAction SilentlyContinue | Remove-Item -Force
